receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  clickhouse:
    endpoint: "http://clickhouse-server:8123"
    database: "otel_metrics"
    username: "otel_user"
    password: "otel_pass"
    async_insert: true
    create_schema: false       # Tables are manually created
    metrics_table_name: "otel_metrics_all"  # Raw table

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]